// <auto-generated />
namespace gameSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class HardCodedShopItems : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HardCodedShopItems));
        
        string IMigrationMetadata.Id
        {
            get { return "202211040321157_HardCodedShopItems"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
